name: Ejarika
description: "Why buy when you can rent? A smart and secure platform for renting and lending items effortlessly."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter_native_splash: ^2.4.0
  image_picker: ^1.1.2
  http: ^0.13.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh-Regular.otf

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/ejarika_logo.png
  fullscreen: true
  android_12: true
  ios: true