flutter_native_splash:
  color: "#1B4965"
  color_dark: "#1B4965"
  image: assets/images/ejarika_logo.png

  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit


  android_12:
    image: assets/images/ejarika_logo.png
    icon_background_color: "#1B4965"
    image_dark: assets/images/ejarika_logo.png
    icon_background_color_dark: "#1B4965"
